// components/ui/icons.tsx
import * as React from "react"
import { SVGProps } from "react"
import {
  Folder,
  MessageSquare,
  Users,
  Heart,
  Trash2,
  Edit,
  Loader2,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  MoreHorizontal,
  X,
  Check,
  Plus,
  Minus,
  Search,
  Settings,
  User,
  LogOut,
  Sun,
  Moon,
  Github,
  Twitter,
  Mail,
  Lock,
  Eye,
  EyeOff,
  AlertCircle,
  ArrowLeft,
  Calendar,
  Clock,
  Home,
  Star,
  FileText,
  Image,
  Download,
  Upload,
  Grid,
  List,
  Filter,
  Columns,
  BarChart2,
  PieChart,
  Share2,
  Copy,
  ExternalLink,
  Link,
  Code,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  ListOrdered,
  Quote,
  Code2,
  Table,
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignJustify,
  Undo,
  Redo,
  Maximize,
  Minimize,
  HelpCircle,
  Info,
  AlertTriangle,
  CheckCircle,
  XCircle,
  PlusCircle,
  MinusCircle,
  Radio,
  CheckSquare,
  Square,
  ToggleLeft,
  ToggleRight,
  Sliders,
  Type,
  Hash,
  Phone,
  CreditCard,
  DollarSign,
  Percent,
  Divide,
  Equal,
  BoldIcon,
  ItalicIcon,
  UnderlineIcon,
  StrikethroughIcon,
  CodeIcon,
  Link2,
  ImageIcon,
  TableIcon,
  ListIcon,
  ListOrderedIcon,
  QuoteIcon,
  AlignLeftIcon,
  AlignCenterIcon,
  AlignRightIcon,
  AlignJustifyIcon,
  Bold as LucideBold,
  Italic as LucideItalic,
  Underline as LucideUnderline,
  Strikethrough as LucideStrikethrough,
  Code as LucideCode,
  Link2 as LucideLink,
  Image as LucideImage,
  Table as LucideTable,
  List as LucideList,
  ListOrdered as LucideListOrdered,
  Quote as LucideQuote,
  AlignLeft as LucideAlignLeft,
  AlignCenter as LucideAlignCenter,
  AlignRight as LucideAlignRight,
  AlignJustify as LucideAlignJustify,
} from "lucide-react"

export const Icons = {
  logo: (props: SVGProps<SVGSVGElement>) => (
    <svg {...props} viewBox="0 0 24 24">
      {/* Your logo SVG path */}
      <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5" />
    </svg>
  ),
  google: (props: SVGProps<SVGSVGElement>) => (
    <svg {...props} viewBox="0 0 24 24">
      <path
        d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z"
        fill="#4285F4"
      />
      <path
        d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z"
        fill="#34A853"
      />
      <path
        d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z"
        fill="#FBBC05"
      />
      <path
        d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z"
        fill="#EA4335"
      />
    </svg>
  ),
  spinner: Loader2,
  refresh: (props: SVGProps<SVGSVGElement>) => (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8" />
      <path d="M21 3v5h-5" />
      <path d="M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16" />
      <path d="M8 16H3v5" />
    </svg>
  ),
  folder: Folder,
  message: MessageSquare,
  users: Users,
  heart: Heart,
  trash: Trash2,
  edit: Edit,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  moreHorizontal: MoreHorizontal,
  close: X,
  check: Check,
  plus: Plus,
  minus: Minus,
  search: Search,
  settings: Settings,
  user: User,
  logOut: LogOut,
  sun: Sun,
  moon: Moon,
  github: Github,
  twitter: Twitter,
  mail: Mail,
  lock: Lock,
  eye: Eye,
  eyeOff: EyeOff,
  alertCircle: AlertCircle,
  arrowLeft: ArrowLeft,
  calendar: Calendar,
  clock: Clock,
  home: Home,
  star: Star,
  fileText: FileText,
  image: Image,
  download: Download,
  upload: Upload,
  grid: Grid,
  list: List,
  filter: Filter,
  columns: Columns,
  barChart: BarChart2,
  pieChart: PieChart,
  share: Share2,
  copy: Copy,
  externalLink: ExternalLink,
  link: Link,
  code: Code,
  bold: Bold,
  italic: Italic,
  underline: Underline,
  strikethrough: Strikethrough,
  listOrdered: ListOrdered,
  quote: Quote,
  table: Table,
  alignLeft: AlignLeft,
  alignCenter: AlignCenter,
  alignRight: AlignRight,
  alignJustify: AlignJustify,
  undo: Undo,
  redo: Redo,
  maximize: Maximize,
  minimize: Minimize,
  helpCircle: HelpCircle,
  info: Info,
  alertTriangle: AlertTriangle,
  checkCircle: CheckCircle,
  xCircle: XCircle,
  plusCircle: PlusCircle,
  minusCircle: MinusCircle,
  radio: Radio,
  checkSquare: CheckSquare,
  square: Square,
  toggleLeft: ToggleLeft,
  toggleRight: ToggleRight,
  sliders: Sliders,
  type: Type,
  hash: Hash,
  phone: Phone,
  creditCard: CreditCard,
  dollarSign: DollarSign,
  percent: Percent,
  divide: Divide,
  equal: Equal,
  // Editor icons
  underlineIcon: UnderlineIcon,
  strikethroughIcon: StrikethroughIcon,
  codeIcon: CodeIcon,
  link2: Link2,
  imageIcon: ImageIcon,
  tableIcon: TableIcon,
  listIcon: ListIcon,
  listOrderedIcon: ListOrderedIcon,
  quoteIcon: QuoteIcon,
  alignLeftIcon: AlignLeftIcon,
  alignCenterIcon: AlignCenterIcon,
  alignRightIcon: AlignRightIcon,
  alignJustifyIcon: AlignJustifyIcon,
  // Lucide icons
  lucideBold: LucideBold,
  lucideItalic: LucideItalic,
  lucideUnderline: LucideUnderline,
  lucideStrikethrough: LucideStrikethrough,
  lucideCode: LucideCode,
  lucideLink: LucideLink,
  lucideImage: LucideImage,
  lucideTable: LucideTable,
  lucideList: LucideList,
  lucideListOrdered: LucideListOrdered,
  lucideQuote: LucideQuote,
  lucideAlignLeft: LucideAlignLeft,
  lucideAlignCenter: LucideAlignCenter,
  lucideAlignRight: LucideAlignRight,
  lucideAlignJustify: LucideAlignJustify,
}